Default: &defaults
  database: workChooser.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: workChooser_test.sqlite3
  <<: *defaults

Staging:
  database: workChooser_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: workChooser_production.sqlite3
  poolsize: 100
  <<: *defaults
